ALTER TYPE "ReportType" ADD VALUE 'PERFORMANCE_REPORT';
ALTER TYPE "ReportType" ADD VALUE 'SEO_REPORT';
ALTER TYPE "ReportType" ADD VALUE 'SECURITY_REPORT';
ALTER TYPE "ReportType" ADD VALUE 'ACCESSIBILITY_REPORT';
